### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [xjtuecho/EBAZ4205#2]
Hello!

I found link to this project from https://hackaday.com/2020/11/18/hacking-the-fpga-control-board-from-a-bitcoin-miner/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by xjtuecho** [comment]
A MIT License has been added. Enjoy it.

**Comment by vazhnov** [comment]
@xjtuecho , great! Thank you!
