### ISSUE TITLE
Establish a Wiki page

### ISSUE THREAD

**Issue by tpecar** [xjtuecho/EBAZ4205#8]
A lot of useful information has already been gathered in the Telegram group, but it would be beneficial to put it in a structured format.

Can you enable the Wiki page on this repository and [change the wiki permissions so that anyone can contribute](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis)?

**Comment by xjtuecho** [comment]
Got it and done.

**Comment by tpecar** [comment]
Thank you.
